get:
  description: Returns all products
  tags:
    - product
  responses:
    '200':
      description: A list of products.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/schemas/product.yaml'
